Tweaking requirements around IDs
openhwgroup/core-v-xif pull request #91
Opened 2023-10-27 08:03 UTC by christian-herber-nxp

... to be unique in flight, incremental wrapping, non-continuous

2023-10-27 08:03 UTC, christian-herber-nxp commented
@jklockars: does this address your input?

2023-10-29 22:36 UTC, jklockars commented
Fine with me, but it seems you are missing a word:
The ``id`` values for in-flight offloaded instructions _are_ required to be unique.

By the way, I see that the ID length is part of the interface specification. As long as it matches between the coprocessor and the core that is fine. But one or the other (well, certainly the coprocessor, at least) might have a preferred minimum size due to the number of possible in-flight operations - should it be mentioned how that is handled/documented, perhaps?

2023-10-30 06:52 UTC, Silabs-ArjanB requested changes

2023-10-30 06:52 UTC, Silabs-ArjanB commented on docs/source/x_ext.rst
> +The ``id`` values for in-flight offloaded instructions required to be unique.
required -> are required

2023-11-01 08:52 UTC, christian-herber-nxp commented
> Fine with me, but it seems you are missing a word: The `id` values for in-flight offloaded instructions _are_ required to be unique.
> 
> By the way, I see that the ID length is part of the interface specification. As long as it matches between the coprocessor and the core that is fine. But one or the other (well, certainly the coprocessor, at least) might have a preferred minimum size due to the number of possible in-flight operations - should it be mentioned how that is handled/documented, perhaps?

fixed in 510637f

2023-11-01 09:13 UTC, christian-herber-nxp commented on docs/source/x_ext.rst
> +The ``id`` values for in-flight offloaded instructions required to be unique.
fixed in 510637f

2023-11-13 18:24 UTC, merged